import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

const appSource = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");
const navigationSource = readFileSync(new URL("../src/data/navigation.ts", import.meta.url), "utf8");
const aiDataSource = readFileSync(new URL("../src/data/stemSeparation.ts", import.meta.url), "utf8");
const aiPageSource = readFileSync(new URL("../src/pages/StemSeparationPage.tsx", import.meta.url), "utf8");
const releasesSource = readFileSync(new URL("../src/pages/ReleasesPage.tsx", import.meta.url), "utf8");
const featuresSource = readFileSync(new URL("../src/pages/FeaturesPage.tsx", import.meta.url), "utf8");
const navbarSource = readFileSync(new URL("../src/components/SiteNavbar.tsx", import.meta.url), "utf8");
const downloadSource = readFileSync(new URL("../src/pages/DownloadPage.tsx", import.meta.url), "utf8");
const cssSource = readFileSync(new URL("../src/index.css", import.meta.url), "utf8");
const aiWebglSource = readFileSync(new URL("../src/components/scene/AiNeuralStudioStage.tsx", import.meta.url), "utf8");
const pretextEditorialSource = readFileSync(
  new URL("../src/components/motion/PretextEditorialField.tsx", import.meta.url),
  "utf8",
);

test("ai is the canonical route and stem-separation redirects for compatibility", () => {
  assert.match(appSource, /<Route path="\/ai" element=\{withPageLoader\(<StemSeparationPage \/>\)\} \/>/);
  assert.match(appSource, /<Route path="\/stem-separation" element=\{<Navigate to="\/ai" replace \/>\} \/>/);
  assert.match(aiDataSource, /path: "\/ai"/);
  assert.match(aiDataSource, /OpenStudio AI/);
});

test("navigation exposes AI instead of stem-only naming", () => {
  assert.match(navigationSource, /\{ label: "AI", to: "\/ai" \}/);
  assert.doesNotMatch(navigationSource, /Stem Separation/);
  assert.match(navbarSource, /site-nav-link/);
  assert.match(cssSource, /\.site-nav-link::after/);
});

test("ai page covers both grounded product pillars", () => {
  assert.match(aiDataSource, /id: "stems"/);
  assert.match(aiDataSource, /BS Roformer 6-stem extraction/);
  assert.match(aiDataSource, /id: "text-audio"/);
  assert.match(aiDataSource, /ACE-Step prompt and lyrics generation/);
  assert.match(aiDataSource, /ACE-Step 1\.5 XL Turbo/);
  assert.match(aiDataSource, /Full VAE decode/);
  assert.match(aiDataSource, /AiNeuralStudioPhase/);
  assert.match(aiDataSource, /aiNeuralStudioPhases/);
  assert.match(aiDataSource, /liquid glass/);
  assert.match(aiDataSource, /glass signal/);
  assert.match(aiDataSource, /six audio waveforms/);
  assert.match(aiDataSource, /prompt, lyrics, and seed/);
  assert.match(aiDataSource, /ACE-Step transforms a prompt waveform/);
  assert.match(aiDataSource, /waveform transform/);
  assert.match(aiDataSource, /generated WAV signal/);
  assert.match(aiDataSource, /shared playhead/);
  assert.match(aiDataSource, /phase-locked waveforms/);
  assert.match(aiDataSource, /timeline alignment/);
  assert.match(aiDataSource, /same x-domain/);
  assert.match(aiDataSource, /multiple visible passes/);
  assert.match(aiDataSource, /phase clock keep them aligned/);
  assert.match(aiDataSource, /sceneBullets/);
  assert.match(aiDataSource, /One thick glass waveform/);
  assert.doesNotMatch(aiDataSource, /generative core/);
  assert.doesNotMatch(aiDataSource, /controlled stem feed/);
  assert.doesNotMatch(aiDataSource, /generated waveform shell/);
  assert.doesNotMatch(aiDataSource, /sonic prism/);
  assert.doesNotMatch(aiDataSource, /lightning forge/);
  assert.match(aiDataSource, /id: "input"/);
  assert.match(aiDataSource, /id: "separate"/);
  assert.match(aiDataSource, /id: "generate"/);
  assert.match(aiDataSource, /id: "commit"/);
  assert.match(aiDataSource, /musicGenerationWorkflowSteps/);
  assert.match(aiDataSource, /musicGenerationControls/);
  assert.match(aiDataSource, /scrollRange/);
  assert.match(aiPageSource, /AiNeuralStudioStage/);
  assert.match(aiPageSource, /NeuralFallbackInstrument/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__liquid/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__currents/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__prompt-filament/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__shockwave/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__ace-transform/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__prompt-wave/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__transform-orb/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__generated-wave/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__waveform-spine/);
  assert.match(aiPageSource, /ai-neural-fallback-instrument__shared-playhead/);
  assert.match(aiPageSource, /NeuralCinematicExplainer/);
  assert.match(aiPageSource, /data-ai-neural-explainer/);
  assert.match(aiPageSource, /data-ai-neural-stem-labels/);
  assert.match(aiPageSource, /data-ai-neural-generation-formula/);
  assert.match(aiPageSource, /data-ai-neural-final-tableau/);
  assert.doesNotMatch(aiPageSource, /StemLanePreview/);
  assert.doesNotMatch(aiPageSource, /PromptWavePreview/);
  assert.doesNotMatch(aiPageSource, /role="tablist"/);
  assert.doesNotMatch(aiPageSource, /useState<AiMode>/);
});

test("ai desktop has a dedicated webgl stage with a reduced mobile fallback", () => {
  assert.match(aiWebglSource, /import \* as THREE from "three"/);
  assert.match(aiWebglSource, /new THREE\.WebGLRenderer/);
  assert.match(aiWebglSource, /ShaderMaterial/);
  assert.match(aiWebglSource, /AiNeuralStudioState/);
  assert.match(aiWebglSource, /data-ai-neural-webgl/);
  assert.match(aiWebglSource, /InstancedMesh/);
  assert.match(aiWebglSource, /makeLiquidMembrane/);
  assert.match(aiWebglSource, /makeSignalLines/);
  assert.match(aiWebglSource, /makeGlints/);
  assert.match(aiWebglSource, /makeStemCurrents/);
  assert.match(aiWebglSource, /updateStemCurrents/);
  assert.match(aiWebglSource, /makeAudioWaveformGeometry/);
  assert.match(aiWebglSource, /updateAudioWaveformGeometry/);
  assert.match(aiWebglSource, /audioWaveformGeometry/);
  assert.match(aiWebglSource, /phaseLockedWaveforms/);
  assert.match(aiWebglSource, /makeMixedSignalBand/);
  assert.match(aiWebglSource, /makePromptFilament/);
  assert.match(aiWebglSource, /makeAceTransformOrb/);
  assert.match(aiWebglSource, /SphereGeometry/);
  assert.match(aiWebglSource, /setAceOrbPosition/);
  assert.match(aiWebglSource, /setAceTransformAnchor/);
  assert.match(aiWebglSource, /promptEntry/);
  assert.match(aiWebglSource, /orbTransform/);
  assert.match(aiWebglSource, /generatedReveal/);
  assert.match(aiWebglSource, /sessionSync/);
  assert.match(aiWebglSource, /makeAceTransformRings/);
  assert.match(aiWebglSource, /makeAceTransformStreams/);
  assert.match(aiWebglSource, /makeAceWaveTransform/);
  assert.match(aiWebglSource, /synchronizedSessionPoint/);
  assert.match(aiWebglSource, /makeRuntimeBoundary/);
  assert.match(aiWebglSource, /makeWaveformSpine/);
  assert.match(aiWebglSource, /makeFinalWaveformRibbon/);
  assert.match(aiWebglSource, /makeSharedPlayhead/);
  assert.match(aiWebglSource, /updateSharedPlayhead/);
  assert.match(aiWebglSource, /sharedPlayhead/);
  assert.match(aiWebglSource, /makeSharedTimeRuler/);
  assert.match(aiWebglSource, /updateSharedTimeRuler/);
  assert.match(aiWebglSource, /sharedTimeRuler/);
  assert.match(aiWebglSource, /commit = easeInOut\(phase\(global, 0\.64, 1\)\)/);
  assert.match(aiWebglSource, /playheadCycle = \(commit \* 3\.35 \+ time \* 0\.035\) % 1/);
  assert.match(aiWebglSource, /-3\.42 \+ u \* 6\.84/);
  assert.match(aiWebglSource, /audioWaveformAmplitude\(u, time, 0\.6, 0\.68\)/);
  assert.match(aiWebglSource, /STEM_CURRENT_COLORS/);
  assert.match(aiWebglSource, /IcosahedronGeometry/);
  assert.match(aiWebglSource, /liquidGlassVertexShader/);
  assert.match(aiWebglSource, /liquidGlassFragmentShader/);
  assert.match(aiWebglSource, /liquidBackdropFragmentShader/);
  assert.match(aiWebglSource, /uEmergence/);
  assert.match(aiWebglSource, /uUnfold/);
  assert.match(aiWebglSource, /uGenerate/);
  assert.match(aiWebglSource, /uCommit/);
  assert.doesNotMatch(aiWebglSource, /makePrism/);
  assert.doesNotMatch(aiWebglSource, /makeForgeBars/);
  assert.doesNotMatch(aiWebglSource, /makeGenerativeCoreSculpture/);
  assert.doesNotMatch(aiWebglSource, /makeGenerativeCoreShellGeometry/);
  assert.match(cssSource, /\.ai-neural-fallback-stage/);
  assert.match(cssSource, /\.ai-neural-mobile-instrument/);
  assert.match(cssSource, /\.ai-neural-stage-wrap/);
  assert.match(cssSource, /\.ai-neural-hud/);
  assert.match(cssSource, /\.ai-neural-explainer/);
  assert.match(cssSource, /\.ai-neural-explainer__stem-labels/);
  assert.match(cssSource, /\.ai-neural-explainer__formula/);
  assert.match(cssSource, /\.ai-neural-explainer__tableau/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__liquid/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__membranes/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__boundary/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__currents/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__prompt-filament/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__shockwave/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__ace-transform/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__prompt-wave/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__transform-orb/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__generated-wave/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__waveform-spine/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__shared-playhead/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__caustics/);
  assert.match(cssSource, /\.ai-neural-fallback-instrument__glints/);
  assert.match(cssSource, /\.ai-neural-lab\s*\{[\s\S]*min-height: 650vh/);
  assert.match(cssSource, /\.ai-neural-mobile-instrument__bullets/);
  assert.match(cssSource, /\.ai-neural-mobile-instrument__stems/);
  assert.match(cssSource, /\.ai-neural-mobile-instrument__formula/);
  assert.match(cssSource, /\.ai-neural-mobile-instrument__tableau/);
  assert.doesNotMatch(cssSource, /\.ai-neural-fallback-instrument__generated-sculpture/);
  assert.doesNotMatch(cssSource, /\.ai-neural-fallback-instrument__prism/);
  assert.doesNotMatch(cssSource, /\.ai-neural-fallback-instrument__forge/);
  assert.match(cssSource, /100svh/);
  assert.match(aiPageSource, /ai-neural-hud__status/);
  assert.doesNotMatch(aiPageSource, /aiHeroStats/);
});

test("ai page has distinct neural studio scroll choreography primitives", () => {
  assert.match(aiPageSource, /ScrollTrigger\.create/);
  assert.match(aiPageSource, /pin: stage/);
  assert.match(aiPageSource, /pinSpacing: false/);
  assert.match(aiPageSource, /data-ai-token/);
  assert.match(aiPageSource, /data-ai-neural-lab/);
  assert.match(aiPageSource, /data-ai-neural-hud/);
  assert.match(aiPageSource, /data-ai-neural-details/);
  assert.doesNotMatch(aiPageSource, /data-ai-story-marker/);
  assert.doesNotMatch(aiPageSource, /data-ai-story-panel/);
  assert.doesNotMatch(aiPageSource, /ai-story-shell/);
  assert.doesNotMatch(aiPageSource, /ai-story-panel/);
  assert.doesNotMatch(aiPageSource, /ChapterProgress/);
  assert.match(aiPageSource, /TokenOrbit/);
  assert.match(cssSource, /\.ai-neural-studio-stage/);
  assert.match(cssSource, /@keyframes ai-token-float/);
  assert.doesNotMatch(cssSource, /\.ai-story-shell/);
  assert.doesNotMatch(cssSource, /\.ai-story-panel/);
});

test("releases reveal animations do not leave permanent hidden states on reverse scroll", () => {
  assert.match(releasesSource, /gsap\.fromTo\(\s*"\[data-release-stage\]"/);
  assert.match(releasesSource, /gsap\.fromTo\(\s*"\[data-release-timeline-card\]"/);
  assert.match(releasesSource, /gsap\.fromTo\(\s*"\[data-release-principle\]"/);
  assert.match(releasesSource, /clearProps: "transform,opacity,visibility"/);
  assert.match(releasesSource, /once: true/);
  assert.match(releasesSource, /ScrollTrigger\.refresh\(\)/);
});

test("features bottom keeps the cta clean after dense details move into the scene", () => {
  assert.match(featuresSource, /FeatureDetailCrawlPanel/);
  assert.match(featuresSource, /chapter\.details\.callouts/);
  assert.match(featuresSource, /chapter\.details\.items/);
  assert.match(featuresSource, /FeatureStoryPanel/);
  assert.match(cssSource, /\.feature-story-detail-crawl-panel/);
  assert.match(cssSource, /\.feature-story-panel/);
  assert.match(pretextEditorialSource, /data-pretext-fragment/);
  assert.match(pretextEditorialSource, /layoutWithLines/);
  assert.match(pretextEditorialSource, /prepareWithSegments/);
  assert.doesNotMatch(featuresSource, /FeatureMusicalSnakesLayer/);
  assert.doesNotMatch(featuresSource, /feature-musical-snakes/);
  assert.doesNotMatch(featuresSource, /data-feature-text-line/);
  assert.match(cssSource, /\.pretext-editorial-field__fragment/);

  const bottomCtaStart = featuresSource.indexOf("feature-story-exit");
  const bottomCtaSource = featuresSource.slice(bottomCtaStart);
  const downloadMentions = bottomCtaSource.match(/Download OpenStudio/g) ?? [];
  assert.equal(downloadMentions.length, 0);
  assert.match(bottomCtaSource, /Explore GitHub/);
});

test("pretext editorial field uses fragment forces and avoids per-frame dom text reads", () => {
  assert.match(pretextEditorialSource, /data-pretext-editorial-field/);
  assert.match(pretextEditorialSource, /IntersectionObserver/);
  assert.match(pretextEditorialSource, /cursorRepel/);
  assert.match(pretextEditorialSource, /data-pretext-force-object/);
  assert.match(pretextEditorialSource, /AI_OBJECT_LABELS = \["signal"\]/);
  assert.doesNotMatch(pretextEditorialSource, /AI_OBJECT_LABELS = \["prompt"/);
  assert.match(pretextEditorialSource, /useReducedMotion/);
  assert.match(pretextEditorialSource, /measureText/);
  assert.doesNotMatch(pretextEditorialSource, /querySelectorAll/);
  assert.doesNotMatch(pretextEditorialSource, /Math\.random/);
});

test("ai bottom uses unlabeled waveform grain kinetic pretext", () => {
  assert.match(aiPageSource, /data-ai-neural-details/);
  assert.match(aiPageSource, /visibleObjects/);
  assert.match(aiPageSource, /AiKineticText/);
  assert.doesNotMatch(aiPageSource, /data-ai-kinetic-line/);
  assert.doesNotMatch(aiPageSource, /usePretextLines/);
  assert.match(cssSource, /\.pretext-editorial-field__object--grain/);
});
test("download source proof uses compact strip instead of oversized card", () => {
  assert.match(downloadSource, /download-source-strip/);
  assert.doesNotMatch(downloadSource, /design-glass-panel rounded-\[2\.5rem\] p-8 md:col-span-8/);
  assert.match(cssSource, /\.download-source-strip__main/);
});
