// Static fixtures for the vendored NAM Rack design port: the parameter
// catalog (mirrors the development mock in OpenStudio's NativeBridge.ts @
// d2056151222fefcede123ef614ec38c6893cbfd5), a loaded rig, runtime status,
// the tuner, and a small capture library. Nothing here changes per frame;
// namRackScript.ts overlays the values that move.
import type { BuiltInParamDescriptor } from "../vendor/stubs/nativeBridgeTypes";

type Row = [id: string, label: string, value: number, min: number, max: number, unit?: string, type?: string];

const ROWS: Row[] = [
  ["inputTrimDb", "Input", 0, -24, 24, "dB"],
  ["instrumentProfile", "Instrument", 0, 0, 1, "", "enum"],
  ["gateThresholdDb", "Gate", -78, -100, 0, "dB"],
  ["gateReleaseMs", "Gate Rel", 80, 20, 500, "ms"],
  ["compressorEnabled", "Compressor", 1, 0, 1, "", "toggle"],
  ["compressorAttackMs", "Attack", 21.9, 0.1, 50, "ms"],
  ["compressorReleaseMs", "Release", 149.1, 50, 1000, "ms"],
  ["compressorToneDb", "Tone", 0, -6, 6, "dB"],
  ["compressorIntensity", "Intensity", 0, 0, 1, "", "toggle"],
  ["compressorSidechainHPF", "HPF", 1, 0, 2, "", "enum"],
  ["compressorMix", "Mix", 0.65, 0, 1],
  ["compressorVolumeDb", "Level", 0, -18, 18, "dB"],
  ["compressorComp", "Comp", 0.35, 0, 1],
  ["octaverEnabled", "Stereo Poly Octaver", 0, 0, 1, "", "toggle"],
  ["octaverDownMix", "Oct -1", 0.32, 0, 1],
  ["octaverUpMix", "Oct +1", 0.18, 0, 1],
  ["octaverDirectMix", "Direct", 1, 0, 1.25],
  ["preEqEnabled", "PRE EQ", 1, 0, 1, "", "toggle"],
  ["preEq120Db", "120 Hz", 0, -12, 12, "dB"],
  ["preEq250Db", "250 Hz", 1.5, -12, 12, "dB"],
  ["preEq500Db", "500 Hz", 0, -12, 12, "dB"],
  ["preEq1kDb", "1 kHz", -1, -12, 12, "dB"],
  ["preEq2k5Db", "2.5 kHz", 2, -12, 12, "dB"],
  ["preEq5kDb", "5 kHz", 0, -12, 12, "dB"],
  ["preEq8kDb", "8 kHz", 0, -12, 12, "dB"],
  ["preEq12kDb", "12 kHz", 0, -12, 12, "dB"],
  ["preEqHPFHz", "PRE HPF", 60, 0, 180, "Hz"],
  ["preEqLPFHz", "PRE LPF", 24000, 3000, 24000, "Hz"],
  ["precisionDriveEnabled", "Precision Drive", 1, 0, 1, "", "toggle"],
  ["precisionDriveVolumeDb", "PD Volume", 9, -12, 12, "dB"],
  ["precisionDriveBright", "PD Bright", 0.55, 0, 1],
  ["precisionDriveAttack", "PD Attack", 0.5, 0, 1],
  ["precisionDriveGate", "PD Gate", 0, 0, 1],
  ["precisionDriveDrive", "PD Drive", 0.35, 0, 1],
  ["chaosEnabled", "Distortion", 0, 0, 1, "", "toggle"],
  ["chaosMode", "Dist Mode", 0, 0, 2, "", "enum"],
  ["chaosDrive", "Dist Drive", 0.62, 0, 1],
  ["chaosWeight", "Weight (Tight to Thick)", 0.5, 0, 1],
  ["chaosTone", "Dist Tone", 0.55, 0, 1],
  ["chaosGate", "Dist Gate", 0.22, 0, 1],
  ["chaosMix", "Dist Mix", 1, 0, 1],
  ["chaosLevelDb", "Dist Level", 0, -12, 12, "dB"],
  ["pedalMix", "Pedal Mix", 1, 0, 1],
  ["ampEnabled", "Amp Power", 1, 0, 1, "", "toggle"],
  ["ampGainDb", "Gain", 0, -24, 24, "dB"],
  ["ampBoost", "Tight Boost", 0, 0, 1, "", "toggle"],
  ["ampVoice", "Bright Voice", 0, 0, 1, "", "toggle"],
  ["ampMix", "Capture Mix", 1, 0, 1],
  ["ampOutputDb", "Post Level", 0, -24, 12, "dB"],
  ["bassDb", "Bass", 0.6, -12, 12, "dB"],
  ["midDb", "Mid", -0.2, -12, 12, "dB"],
  ["trebleDb", "Treble", 1.8, -12, 12, "dB"],
  ["presenceDb", "Presence", 1.2, -12, 12, "dB"],
  ["eqHPFHz", "HPF", 0, 0, 500, "Hz"],
  ["eq65Db", "65 Hz", 0, -12, 12, "dB"],
  ["eq125Db", "125 Hz", 1, -12, 12, "dB"],
  ["eq250Db", "250 Hz", 0, -12, 12, "dB"],
  ["eq500Db", "500 Hz", -1.5, -12, 12, "dB"],
  ["eq1kDb", "1 kHz", 0, -12, 12, "dB"],
  ["eq2kDb", "2 kHz", 1.5, -12, 12, "dB"],
  ["eq4kDb", "4 kHz", 2, -12, 12, "dB"],
  ["eq8kDb", "8 kHz", 0.5, -12, 12, "dB"],
  ["eq16kDb", "16 kHz", 0, -12, 12, "dB"],
  ["eqLPFHz", "LPF", 24000, 3000, 24000, "Hz"],
  ["eqLevelDb", "Level", 0, -12, 12, "dB"],
  ["eqEnabled", "EQ Power", 1, 0, 1, "", "toggle"],
  ["cabEnabled", "Cab/IR", 1, 0, 1, "", "toggle"],
  ["cabLevelDb", "Cab Level", -0.5, -24, 12, "dB"],
  ["cabHPFHz", "Cab HPF", 80, 20, 500, "Hz"],
  ["cabLPFHz", "Cab LPF", 8500, 2500, 14000, "Hz"],
  ["cabPhaseInvert", "Phase", 0, 0, 1, "", "toggle"],
  ["cabMicPosition", "Tone Edge", 0.5, 0, 1],
  ["cabMicDistance", "Tone Damp", 0, 0, 1],
  ["cabMicBlend", "Shaper Blend", 0.5, 0, 1],
  ["cabRoomSend", "Low Bloom", 0, 0, 1],
  ["cabRoomEnabled", "Room", 1, 0, 1, "", "toggle"],
  ["cabRoomAmount", "Room Amount", 0.22, 0, 1],
  ["cabRoomWidth", "Room Width", 0.65, 0, 1],
  ["cabDoublerEnabled", "Doubler", 0, 0, 1, "", "toggle"],
  ["cabDoublerMix", "Doubler Mix", 0.12, 0, 1],
  ["cabDoublerDelayMs", "Doubler Delay", 4.5, 3, 20, "ms"],
  ["cabDoublerSpread", "Doubler Spread", 0.65, 0, 1],
  ["cabPan", "Cab Pan", 0, -1, 1],
  ["chorusMix", "Chorus Mix", 0.3, 0, 1],
  ["chorusRateHz", "Chorus Rate", 0.75, 0.01, 8, "Hz"],
  ["chorusDepth", "Chorus Depth", 0.32, 0, 1],
  ["chorusCharacter", "Character", 1, 0, 1, "", "enum"],
  ["modulatorMode", "Mod Mode", 0, 0, 1, "", "enum"],
  ["modulatorFeedback", "Mod Feedback", 0.1, 0, 1],
  ["modulatorAutoRandom", "Auto Random", 0, 0, 1],
  ["modulatorAutoSpeed", "Auto Speed", 0.35, 0, 1],
  ["modulatorEnabled", "Mod Engage", 1, 0, 1, "", "toggle"],
  ["modulatorPedalMode", "Pedal Mode", 1, 0, 1, "", "enum"],
  ["modulatorPedalPosition", "Pedal Sweep", 0.5, 0, 1],
  ["delayMix", "Delay Mix", 0.22, 0, 1],
  ["delayTimeMs", "Delay Time", 360, 1, 2000, "ms"],
  ["delayFeedback", "Delay Fdbk", 0.22, 0, 0.85],
  ["delayMod", "Delay Mod", 0.18, 0, 1],
  ["delayDucker", "Ducker", 0.12, 0, 1],
  ["delayMode", "Delay Mode", 1, 0, 4, "", "enum"],
  ["delayPingPong", "Ping Pong", 1, 0, 1, "", "toggle"],
  ["delayTempoSync", "Delay Sync", 0, 0, 1, "", "toggle"],
  ["delayEnabled", "Delay Engage", 1, 0, 1, "", "toggle"],
  ["reverbEnabled", "Reverb Engage", 1, 0, 1, "", "toggle"],
  ["reverbVoice", "Reverb Voice", 1, 0, 3, "", "enum"],
  ["reverbMix", "Reverb Mix", 0.28, 0, 1],
  ["reverbDecaySec", "Decay", 2.2, 0.2, 12, "s"],
  ["reverbPreDelayMs", "Pre Delay", 18, 0, 500, "ms"],
  ["reverbLowCutHz", "Low Cut", 120, 20, 500, "Hz"],
  ["reverbTone", "Verb Tone", 0.62, 0, 1],
  ["reverbShimmer", "Shimmer", 0, 0, 1],
  ["reverbPad", "Pad", 0, 0, 1, "", "toggle"],
  ["outputTrimDb", "Output", -0.5, -24, 24, "dB"],
];

const ENUM_OPTIONS: Record<string, string[]> = {
  instrumentProfile: ["Guitar", "Bass"],
  compressorSidechainHPF: ["Off", "80 Hz", "240 Hz"],
  chaosMode: ["Heavy", "Extreme", "Crunch"],
  chorusCharacter: ["Classic", "Modern"],
  modulatorMode: ["Chorus", "Flanger"],
  modulatorPedalMode: ["Sweep", "Auto"],
  delayMode: ["Digital", "Tape", "Analog", "Reverse", "Ping"],
  reverbVoice: ["Studio", "Plate", "Hall", "Room"],
};

export const NAM_PARAMS: readonly BuiltInParamDescriptor[] = ROWS.map(([id, label, value, min, max, unit = "", type = "continuous"]) => ({
  id,
  label,
  type,
  value,
  min,
  max,
  defaultValue: value,
  unit,
  automatable: true,
  graphRole: "controls",
  enumOptions: type === "enum" ? ENUM_OPTIONS[id]?.map((name, index) => ({ value: index, label: name })) : undefined,
}));

/** Descriptors with the moving values applied, preserving identity for untouched ones. */
export const withValues = (values: Record<string, number>): BuiltInParamDescriptor[] =>
  NAM_PARAMS.map((param) => (param.id in values && values[param.id] !== param.value ? { ...param, value: values[param.id] } : param));

export const RIG = {
  presetName: "Clean Twin Style A2",
  presetEyebrow: "Factory tone · Guitar",
  presetDirty: false,
  pedalLabel: "Precision Drive",
  hasPedalCapture: true,
  ampLabel: "Clean Twin Style A2",
  cabLabel: "4×12 V30 · SM57",
  cabStatus: "IR loaded",
  hasAmpCapture: true,
  ampCaptureMissing: false,
  hasCabIR: true,
  cabMode: "loaded" as const,
  cabRoomInputSourceAvailable: true,
};

export const RUNTIME = {
  tempo: 120,
  timeSignatureLabel: "4/4",
  sampleRateLabel: "48 kHz",
  bufferLabel: "128",
  latencyLabel: "5.3 ms",
  cpuLabel: "6 %",
  dspLabel: "A2 · full",
  diagnosticTone: "success" as const,
  diagnosticMessage: "Model loaded",
  inputChannelCount: 1,
};

export const LIBRARY = [
  { id: "crisp", name: "Crisp Twin Clean A2", subtitle: "Fender-style clean · 2 captures", active: true },
  { id: "edge", name: "Edge Clean A1", subtitle: "Edge-of-breakup · amp only" },
  { id: "jc", name: "JC Glass A2", subtitle: "Solid-state clean · cab embedded" },
  { id: "plexi", name: "Plexi Crunch A2", subtitle: "British crunch · 4 captures" },
];

export const TUNER_REST = {
  signalPresent: false,
  pitchLocked: false,
  noteLabel: "—",
  statusLabel: "Listening",
  centsPct: 0,
  frequencyLabel: "— Hz",
  inputLevelLabel: "−∞ dB",
  confidenceLabel: "0 %",
};
