// SVG re-draw of the clip renderers in OpenStudio frontend/src/components/
// Timeline.tsx (renderClip, renderMIDIClip, renderCompactMIDIThumbnail,
// renderRecordingClip @ d2056151222fefcede123ef614ec38c6893cbfd5). Upstream
// draws with react-konva; the same rectangles, opacities, strokes and text
// offsets are drawn here as plain SVG, with peaks and notes generated by
// clipArt.ts instead of fetched from the engine.
import { memo, useMemo } from "react";
import { audioPeaks, midiNotes, waveformPolygon, type AudioProfile, type MidiProfile } from "./clipArt";

interface ClipGeometry {
  /** Clip width in px. */
  width: number;
  /** Clip height in px (rowMetrics.clipHeight). */
  height: number;
  color: string;
}

/* ---------------- audio ---------------- */

interface AudioClipLiteProps extends ClipGeometry {
  name: string;
  profile: AudioProfile;
  seed: number;
  pixelsPerSecond: number;
  duration: number;
  tempo: number;
  /** Seconds of source before the clip's first pixel (split clips). */
  offset?: number;
  muted?: boolean;
  /** The take-in-progress look: solid border, REC badge, denser fill. */
  recording?: boolean;
}

export const AudioClipLite = memo(function AudioClipLite({
  width,
  height,
  color,
  name,
  profile,
  seed,
  pixelsPerSecond,
  duration,
  tempo,
  offset = 0,
  muted = false,
  recording = false,
}: AudioClipLiteProps) {
  const waveformHeight = Math.max(8, height - 10);
  const channelHeight = waveformHeight / 2;
  const halfHeight = channelHeight / 2 - 2;
  const peaks = useMemo(() => audioPeaks(profile, seed, width, pixelsPerSecond, duration, tempo, offset), [profile, seed, width, pixelsPerSecond, duration, tempo, offset]);
  const polygons = useMemo(
    () => [0, 1].map((channel) => waveformPolygon(peaks, channel as 0 | 1, 5 + channel * channelHeight + channelHeight / 2, halfHeight)),
    [peaks, channelHeight, halfHeight],
  );
  const fillOpacity = muted ? 0.12 : recording ? 0.3 : 0.18;
  const waveOpacity = recording ? 0.8 : 0.6;
  const rounded = recording ? 3 : 4;

  return (
    <svg aria-hidden="true" className="absolute inset-0 block overflow-visible" height={height} width={Math.max(0, width)}>
      <rect fill={color} height={height} opacity={fillOpacity} rx={rounded} width={width} />
      {!muted && !recording && <rect fill="#ffffff" height={Math.min(12, height / 3)} opacity={0.04} rx={4} width={width} />}
      {!muted &&
        polygons.map((points, channel) => (
          <polygon key={channel} fill={color} opacity={waveOpacity} points={points} stroke={color} strokeLinejoin="round" strokeWidth={recording ? 0.5 : 1} />
        ))}
      {muted && (
        <>
          <rect fill="#000000" height={height} opacity={0.24} rx={3} width={width} />
          <g opacity={0.12} stroke={color} strokeWidth={1}>
            {Array.from({ length: Math.ceil(width / 12) + 1 }).map((_, i) => (
              <line key={i} x1={i * 12} x2={i * 12 - height} y1={0} y2={height} />
            ))}
          </g>
        </>
      )}
      <rect fill="none" height={height - (recording ? 1 : 0.5)} rx={3} stroke={recording ? color : muted ? "#666" : "#fff"} strokeWidth={recording ? 1 : 0.5} width={width - (recording ? 1 : 0.5)} x={recording ? 0.5 : 0.25} y={recording ? 0.5 : 0.25} />
      {recording ? (
        <>
          <text fill="#fff" fontSize={10} fontWeight="bold" x={5} y={12}>
            REC
          </text>
          <circle className="recording-dot" cx={35} cy={8} fill="#ff3333" r={4} />
        </>
      ) : (
        <ClipName height={height} muted={muted} name={name} width={width} />
      )}
    </svg>
  );
});

const ClipName = ({ name, width, muted, midi = false }: { name: string; width: number; height: number; muted?: boolean; midi?: boolean }) => (
  <foreignObject height={14} width={Math.max(0, width - (midi && width < 60 ? 4 : 10))} x={midi && width < 60 ? 2 : 5} y={3}>
    <span
      className="block truncate leading-[12px] whitespace-nowrap"
      style={{ fontSize: midi && width < 60 ? 9 : 10, color: muted ? "#888" : "#fff", fontFamily: "inherit" }}
    >
      {midi ? (width < 60 ? "♪" : `♪ ${name}`) : name}
    </span>
  </foreignObject>
);

/* ---------------- MIDI ---------------- */

interface MidiClipLiteProps extends ClipGeometry {
  name: string;
  profile: MidiProfile;
  seed: number;
  pixelsPerSecond: number;
  duration: number;
  tempo: number;
  offset?: number;
  muted?: boolean;
  selected?: boolean;
  recording?: boolean;
}

export const MidiClipLite = memo(function MidiClipLite({
  width,
  height,
  color,
  name,
  profile,
  seed,
  pixelsPerSecond,
  duration,
  tempo,
  offset = 0,
  muted = false,
  selected = false,
  recording = false,
}: MidiClipLiteProps) {
  const previewHeight = Math.max(8, height - 10);
  const narrow = width < 60;
  // Notes for the whole source; a growing (recording) or split clip shows its window.
  const source = useMemo(() => midiNotes(profile, seed, offset + duration + 0.001, tempo), [profile, seed, offset, duration, tempo]);
  const bars = useMemo(() => {
    const visible = source
      .filter((note) => note.start + note.duration > offset && note.start < offset + duration)
      .map((note) => ({ note: note.note, start: Math.max(0, note.start - offset), end: Math.min(duration, note.start + note.duration - offset) }));
    if (visible.length === 0) return [];
    const pitches = visible.map((bar) => bar.note);
    const minNote = Math.min(...pitches);
    const maxNote = Math.max(...pitches);
    const noteRange = Math.max(1, maxNote - minNote);
    const safeDuration = Math.max(duration, 0.001);
    return visible.map((bar) => ({
      x: (bar.start / safeDuration) * width,
      width: Math.max(narrow ? 1 : 2, ((Math.max(bar.end, bar.start) - bar.start) / safeDuration) * width),
      y: 5 + ((maxNote - bar.note) / noteRange) * (previewHeight - 4),
      height: narrow ? Math.max(1.5, Math.min(3, previewHeight / noteRange)) : Math.max(2, Math.min(previewHeight / noteRange, 4)),
    }));
  }, [source, offset, duration, width, previewHeight, narrow]);
  void pixelsPerSecond;

  const handleFill = selected ? "#d9f4ff" : "rgba(255,255,255,0.42)";

  return (
    <svg aria-hidden="true" className="absolute inset-0 block overflow-visible" height={height} width={Math.max(0, width)}>
      <rect fill={color} height={height} opacity={recording ? 0.3 : muted ? 0.14 : 0.25} rx={3} width={width} />
      {bars.map((bar, index) => (
        <rect key={index} fill={color} height={bar.height} opacity={muted ? (narrow ? 0.45 : 0.4) : narrow ? 0.9 : 0.8} width={bar.width} x={bar.x} y={bar.y} />
      ))}
      <rect
        fill="none"
        height={height - (selected ? 1.5 : 0.75)}
        rx={3}
        stroke={recording ? color : selected ? "#d9f4ff" : muted ? "#666" : "rgba(255,255,255,0.68)"}
        strokeWidth={recording ? 1 : selected ? 1.5 : 0.75}
        width={width - (selected ? 1.5 : 0.75)}
        x={selected ? 0.75 : 0.375}
        y={selected ? 0.75 : 0.375}
      />
      {width >= 18 && !recording && (
        <>
          <rect fill={handleFill} height={height - 4} opacity={muted ? 0.35 : 0.85} rx={2} width={4} x={0} y={2} />
          <rect fill={handleFill} height={height - 4} opacity={muted ? 0.35 : 0.85} rx={2} width={4} x={width - 4} y={2} />
        </>
      )}
      {recording ? (
        <>
          <text fill="#fff" fontSize={10} fontWeight="bold" x={5} y={12}>
            REC
          </text>
          <circle className="recording-dot" cx={35} cy={8} fill="#ff3333" r={4} />
        </>
      ) : (
        <ClipName height={height} midi muted={muted} name={name} width={width} />
      )}
    </svg>
  );
});
