[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/download/windows/latest"
  to = "/.netlify/functions/download-latest?platform=windows"
  status = 200
  force = true

[[redirects]]
  from = "/download/macos/latest"
  to = "/.netlify/functions/download-latest?platform=macos"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
